-- m_icon."keyword" — kata kunci bahasa Indonesia untuk pencarian ikon.
--
-- Isinya gabungan terjemahan dari kolom "nama" ditambah kata yang menggambarkan
-- BENTUK ikonnya, dipisah koma. Contoh: armchair → "kursi, sofa, bangku, furnitur",
-- sehingga mengetik "bangku" tetap menemukan ikon tersebut.
--
-- Dipakai oleh pencarian ikon di Kategori Keuangan, Fasilitas Aset, Fasilitas
-- Item Aset, dan Master Icon.

ALTER TABLE "m_icon" ADD COLUMN IF NOT EXISTS "keyword" TEXT;

UPDATE "m_icon" AS m
SET "keyword" = v.kw
FROM (
  VALUES
    ('tabler-home', 'rumah, beranda, hunian, tempat tinggal'),
    ('tabler-dashboard', 'dasbor, dashboard, panel, ringkasan'),
    ('tabler-menu', 'menu, garis, daftar, navigasi'),
    ('tabler-menu-2', 'menu, garis, daftar, navigasi'),
    ('tabler-dots', 'titik, opsi, lainnya, menu'),
    ('tabler-dots-vertical', 'titik, opsi, lainnya, menu, vertikal'),
    ('tabler-chevron-down', 'panah bawah, turun, buka'),
    ('tabler-chevron-up', 'panah atas, naik, tutup'),
    ('tabler-chevron-left', 'panah kiri, sebelumnya'),
    ('tabler-chevron-right', 'panah kanan, berikutnya'),
    ('tabler-arrow-left', 'panah kiri, kembali, mundur'),
    ('tabler-arrow-right', 'panah kanan, lanjut, maju'),
    ('tabler-arrow-up', 'panah atas, naik'),
    ('tabler-arrow-down', 'panah bawah, turun'),
    ('tabler-x', 'silang, tutup, batal, hapus'),
    ('tabler-check', 'centang, ceklis, benar, setuju, selesai'),
    ('tabler-plus', 'tambah, plus, baru'),
    ('tabler-minus', 'kurang, minus, hapus'),
    ('tabler-search', 'cari, pencarian, kaca pembesar, lup'),
    ('tabler-filter', 'filter, saring, corong'),
    ('tabler-settings', 'pengaturan, setelan, gerigi, roda gigi'),
    ('tabler-adjustments', 'pengaturan, penyesuaian, slider, kontrol'),
    ('tabler-user', 'pengguna, orang, akun, profil'),
    ('tabler-users', 'pengguna, orang, grup, kelompok, tim'),
    ('tabler-user-plus', 'tambah pengguna, undang, anggota baru'),
    ('tabler-user-minus', 'hapus pengguna, keluarkan anggota'),
    ('tabler-user-check', 'pengguna disetujui, terverifikasi'),
    ('tabler-user-x', 'pengguna ditolak, blokir'),
    ('tabler-user-circle', 'profil, akun, avatar, foto pengguna'),
    ('tabler-friends', 'teman, dua orang, pasangan'),
    ('tabler-mood-happy', 'senang, gembira, emoji, wajah'),
    ('tabler-mood-sad', 'sedih, emoji, wajah'),
    ('tabler-mood-smile', 'senyum, emoji, wajah'),
    ('tabler-building', 'gedung, bangunan, kantor, properti'),
    ('tabler-building-store', 'toko, warung, ruko, kios, gerai'),
    ('tabler-building-bank', 'bank, gedung, keuangan, lembaga'),
    ('tabler-building-factory', 'pabrik, industri, manufaktur'),
    ('tabler-building-warehouse', 'gudang, penyimpanan, stok'),
    ('tabler-cash', 'uang, tunai, kas, duit, lembaran'),
    ('tabler-coin', 'koin, uang logam, receh'),
    ('tabler-currency-dollar', 'dolar, mata uang, uang'),
    ('tabler-currency-euro', 'euro, mata uang, uang'),
    ('tabler-currency-pound', 'pound, mata uang, uang'),
    ('tabler-currency-rupee', 'rupee, mata uang, uang'),
    ('tabler-credit-card', 'kartu kredit, kartu debit, pembayaran, atm'),
    ('tabler-wallet', 'dompet, saldo, uang'),
    ('tabler-receipt', 'struk, kuitansi, nota, tagihan, invoice'),
    ('tabler-chart-line', 'grafik garis, statistik, laporan, tren'),
    ('tabler-chart-bar', 'grafik batang, diagram, statistik'),
    ('tabler-chart-pie', 'diagram lingkaran, grafik pai, statistik'),
    ('tabler-chart-histogram', 'histogram, grafik, statistik'),
    ('tabler-trending-up', 'naik, meningkat, untung, tren naik'),
    ('tabler-trending-down', 'turun, menurun, rugi, tren turun'),
    ('tabler-report', 'laporan, dokumen, berkas'),
    ('tabler-report-analytics', 'laporan analitik, statistik, analisis'),
    ('tabler-home-dollar', 'harga rumah, sewa rumah, properti dijual'),
    ('tabler-home-2', 'rumah, hunian, tempat tinggal'),
    ('tabler-smart-home', 'rumah pintar, otomatis, smart home'),
    ('tabler-door', 'pintu, kamar, akses, masuk'),
    ('tabler-bed', 'kasur, tempat tidur, kamar, kos, ranjang'),
    ('tabler-armchair', 'kursi, sofa, bangku, furnitur, perabot'),
    ('tabler-bath', 'kamar mandi, bak mandi, wc, toilet'),
    ('tabler-key', 'kunci, akses, sewa'),
    ('tabler-lock', 'gembok, kunci, terkunci, aman'),
    ('tabler-lock-open', 'gembok terbuka, tidak terkunci, akses'),
    ('tabler-mail', 'surat, email, amplop, pesan'),
    ('tabler-message', 'pesan, chat, obrolan, komentar'),
    ('tabler-message-circle', 'pesan, chat, obrolan, komentar'),
    ('tabler-phone', 'telepon, hp, kontak, gagang telepon'),
    ('tabler-phone-call', 'panggilan, telepon, hubungi'),
    ('tabler-bell', 'lonceng, notifikasi, pemberitahuan'),
    ('tabler-bell-ringing', 'lonceng berbunyi, notifikasi, alarm'),
    ('tabler-notification', 'notifikasi, pemberitahuan, pesan'),
    ('tabler-send', 'kirim, pesawat kertas, pesan'),
    ('tabler-inbox', 'kotak masuk, inbox, surat'),
    ('tabler-file', 'berkas, file, dokumen, kertas'),
    ('tabler-file-text', 'dokumen, berkas teks, kertas'),
    ('tabler-file-plus', 'tambah berkas, dokumen baru'),
    ('tabler-file-minus', 'hapus berkas, kurangi dokumen'),
    ('tabler-files', 'berkas, banyak dokumen, arsip'),
    ('tabler-folder', 'folder, map, direktori'),
    ('tabler-folder-plus', 'tambah folder, map baru'),
    ('tabler-clipboard', 'papan klip, salin, catatan'),
    ('tabler-clipboard-list', 'daftar, ceklis, catatan, checklist'),
    ('tabler-notes', 'catatan, memo, nota'),
    ('tabler-notebook', 'buku catatan, agenda, jurnal'),
    ('tabler-book', 'buku, panduan, bacaan'),
    ('tabler-bookmark', 'penanda, markah, simpan, pembatas buku'),
    ('tabler-photo', 'foto, gambar, galeri'),
    ('tabler-camera', 'kamera, foto, potret'),
    ('tabler-video', 'video, rekaman, kamera'),
    ('tabler-music', 'musik, lagu, not balok, audio'),
    ('tabler-microphone', 'mikrofon, rekam, suara'),
    ('tabler-volume', 'suara, volume, speaker'),
    ('tabler-volume-2', 'suara, volume, speaker, keras'),
    ('tabler-play', 'putar, mainkan, segitiga'),
    ('tabler-pause', 'jeda, pause, berhenti sementara'),
    ('tabler-stop', 'berhenti, stop, kotak'),
    ('tabler-download', 'unduh, download, simpan'),
    ('tabler-upload', 'unggah, upload, kirim berkas'),
    ('tabler-cloud', 'awan, cloud, mendung'),
    ('tabler-cloud-upload', 'unggah cloud, upload awan'),
    ('tabler-cloud-download', 'unduh cloud, download awan'),
    ('tabler-edit', 'ubah, edit, sunting, pensil'),
    ('tabler-pencil', 'pensil, tulis, edit, coret'),
    ('tabler-eraser', 'penghapus, hapus, karet'),
    ('tabler-trash', 'tong sampah, hapus, buang, keranjang sampah'),
    ('tabler-copy', 'salin, duplikat, copy'),
    ('tabler-cut', 'potong, gunting'),
    ('tabler-paste', 'tempel, paste, papan klip'),
    ('tabler-save', 'simpan, disket, save'),
    ('tabler-printer', 'printer, cetak, mesin cetak'),
    ('tabler-scan', 'pindai, scan, pemindai'),
    ('tabler-qrcode', 'kode qr, qris, pindai, barcode'),
    ('tabler-barcode', 'barcode, kode batang, pindai'),
    ('tabler-shield', 'perisai, keamanan, proteksi, tameng'),
    ('tabler-shield-check', 'aman, terverifikasi, perisai, terlindungi'),
    ('tabler-shield-lock', 'keamanan, terkunci, perisai, privasi'),
    ('tabler-eye', 'mata, lihat, tampilkan, pratinjau'),
    ('tabler-eye-off', 'sembunyikan, mata tertutup, rahasia'),
    ('tabler-fingerprint', 'sidik jari, biometrik, keamanan'),
    ('tabler-password', 'kata sandi, password, keamanan'),
    ('tabler-alert-circle', 'peringatan, perhatian, awas'),
    ('tabler-alert-triangle', 'peringatan, awas, segitiga, bahaya'),
    ('tabler-info-circle', 'informasi, keterangan, info'),
    ('tabler-help', 'bantuan, tanya, pertolongan'),
    ('tabler-question-mark', 'tanda tanya, bantuan, pertanyaan'),
    ('tabler-circle-check', 'berhasil, sukses, centang, selesai'),
    ('tabler-circle-x', 'gagal, batal, silang, ditolak'),
    ('tabler-exclamation-mark', 'tanda seru, peringatan, penting'),
    ('tabler-calendar', 'kalender, tanggal, jadwal, penanggalan'),
    ('tabler-calendar-event', 'jadwal, acara, agenda, event'),
    ('tabler-clock', 'jam, waktu, jam dinding'),
    ('tabler-alarm', 'alarm, pengingat, jam weker'),
    ('tabler-hourglass', 'jam pasir, menunggu, waktu, proses'),
    ('tabler-history', 'riwayat, histori, log'),
    ('tabler-map', 'peta, lokasi, denah'),
    ('tabler-map-pin', 'penanda lokasi, pin, alamat, titik lokasi'),
    ('tabler-location', 'lokasi, posisi, gps, navigasi'),
    ('tabler-compass', 'kompas, arah, penunjuk arah'),
    ('tabler-route', 'rute, jalur, perjalanan'),
    ('tabler-directions', 'petunjuk arah, rute, rambu'),
    ('tabler-shopping-cart', 'keranjang belanja, troli, belanja'),
    ('tabler-shopping-bag', 'tas belanja, kantong belanja'),
    ('tabler-basket', 'keranjang, belanja, bakul'),
    ('tabler-gift', 'hadiah, kado, bonus, bingkisan'),
    ('tabler-tag', 'label, tag, harga, banderol'),
    ('tabler-tags', 'label, tag, kategori, banderol'),
    ('tabler-ticket', 'tiket, karcis, voucher, kupon'),
    ('tabler-package', 'paket, kardus, kiriman, bungkusan'),
    ('tabler-box', 'kotak, kardus, dus, wadah'),
    ('tabler-truck-delivery', 'truk, pengiriman, kirim, ekspedisi'),
    ('tabler-share', 'bagikan, share, sebar'),
    ('tabler-heart', 'hati, suka, favorit, cinta'),
    ('tabler-star', 'bintang, favorit, rating, penilaian'),
    ('tabler-thumb-up', 'jempol, suka, setuju, bagus'),
    ('tabler-thumb-down', 'jempol bawah, tidak suka, tolak'),
    ('tabler-flag', 'bendera, tandai, laporkan'),
    ('tabler-device-desktop', 'komputer, pc, monitor, layar'),
    ('tabler-device-laptop', 'laptop, notebook, komputer jinjing'),
    ('tabler-device-mobile', 'hp, ponsel, handphone, smartphone'),
    ('tabler-device-tablet', 'tablet, ipad, layar sentuh'),
    ('tabler-wifi', 'wifi, internet, jaringan, sinyal'),
    ('tabler-bluetooth', 'bluetooth, koneksi, nirkabel'),
    ('tabler-usb', 'usb, flashdisk, colokan'),
    ('tabler-plug', 'colokan, steker, listrik, stopkontak'),
    ('tabler-battery', 'baterai, daya, aki'),
    ('tabler-battery-charging', 'baterai mengisi, cas, pengisian daya'),
    ('tabler-cpu', 'prosesor, cpu, chip'),
    ('tabler-server', 'server, basis data, pusat data'),
    ('tabler-palette', 'palet, warna, cat, lukis'),
    ('tabler-brush', 'kuas, cat, lukis, sapuan'),
    ('tabler-color-picker', 'pemilih warna, pipet, warna'),
    ('tabler-paint', 'cat, kaleng cat, pengecatan'),
    ('tabler-layers', 'lapisan, layer, tumpukan'),
    ('tabler-layout', 'tata letak, layout, susunan'),
    ('tabler-template', 'templat, template, contoh, pola'),
    ('tabler-grid-dots', 'kisi, grid, titik, susunan'),
    ('tabler-square', 'persegi, kotak, bujur sangkar'),
    ('tabler-circle', 'lingkaran, bulat, bundar'),
    ('tabler-triangle', 'segitiga, bentuk'),
    ('tabler-sun', 'matahari, siang, cerah, terang'),
    ('tabler-moon', 'bulan, malam, gelap'),
    ('tabler-cloud-rain', 'hujan, awan, cuaca'),
    ('tabler-cloud-snow', 'salju, awan, cuaca dingin'),
    ('tabler-wind', 'angin, udara, berangin'),
    ('tabler-temperature', 'suhu, termometer, temperatur'),
    ('tabler-leaf', 'daun, tanaman, hijau, alam'),
    ('tabler-plant', 'tanaman, tumbuhan, pot, kebun'),
    ('tabler-tree', 'pohon, taman, alam'),
    ('tabler-coffee', 'kopi, cangkir, minuman, kafe'),
    ('tabler-cup', 'cangkir, gelas, minuman'),
    ('tabler-pizza', 'pizza, makanan, kuliner'),
    ('tabler-apple', 'apel, buah, makanan'),
    ('tabler-lemon', 'lemon, jeruk, buah'),
    ('tabler-ball-basketball', 'bola basket, olahraga, lapangan'),
    ('tabler-ball-football', 'bola sepak, sepakbola, olahraga, futsal'),
    ('tabler-bike', 'sepeda, olahraga, kendaraan'),
    ('tabler-run', 'lari, olahraga, berlari'),
    ('tabler-walk', 'jalan kaki, olahraga, berjalan'),
    ('tabler-star-filled', 'bintang penuh, favorit, rating, penilaian'),
    ('tabler-heart-filled', 'hati penuh, suka, favorit, cinta'),
    ('tabler-circle-filled', 'lingkaran penuh, bulat, titik'),
    ('tabler-square-filled', 'persegi penuh, kotak, blok'),
    ('tabler-infinity', 'tak terbatas, infinity, selamanya'),
    ('tabler-hash', 'pagar, tagar, hashtag, nomor'),
    ('tabler-at', 'at, email, keong, alamat surel'),
    ('tabler-percentage', 'persen, diskon, potongan'),
    ('tabler-arrow-narrow-up', 'panah atas, naik, tipis'),
    ('tabler-arrow-narrow-down', 'panah bawah, turun, tipis'),
    ('tabler-arrow-narrow-left', 'panah kiri, tipis'),
    ('tabler-arrow-narrow-right', 'panah kanan, tipis'),
    ('tabler-arrows-maximize', 'perbesar, layar penuh, bentangkan'),
    ('tabler-arrows-minimize', 'perkecil, keluar layar penuh, ciutkan'),
    ('tabler-refresh', 'muat ulang, segarkan, refresh, perbarui'),
    ('tabler-rotate', 'putar, rotasi, balik'),
    ('tabler-flip-horizontal', 'balik horizontal, cermin, mendatar'),
    ('tabler-flip-vertical', 'balik vertikal, cermin, tegak'),
    ('tabler-brand-facebook', 'facebook, media sosial, fb'),
    ('tabler-brand-twitter', 'twitter, media sosial, x'),
    ('tabler-brand-instagram', 'instagram, media sosial, ig'),
    ('tabler-brand-linkedin', 'linkedin, media sosial, profesional'),
    ('tabler-brand-youtube', 'youtube, video, media sosial'),
    ('tabler-brand-google', 'google, mesin pencari'),
    ('tabler-brand-github', 'github, kode, repositori'),
    ('tabler-brand-whatsapp', 'whatsapp, wa, chat, pesan'),
    ('tabler-favicon', 'favicon, ikon situs, logo web'),
    ('tabler-atom', 'atom, sains, ilmu pengetahuan'),
    ('tabler-award', 'penghargaan, medali, piala, juara'),
    ('tabler-badge', 'lencana, badge, tanda'),
    ('tabler-certificate', 'sertifikat, ijazah, piagam'),
    ('tabler-crown', 'mahkota, raja, premium, utama'),
    ('tabler-diamond', 'berlian, permata, premium, intan'),
    ('tabler-flame', 'api, nyala, populer, terbakar'),
    ('tabler-lightning', 'petir, kilat, cepat, listrik'),
    ('tabler-magnet', 'magnet, tarik, daya tarik'),
    ('tabler-puzzle', 'puzzle, teka-teki, kepingan'),
    ('tabler-rocket', 'roket, peluncuran, cepat, mulai'),
    ('tabler-sparkles', 'kilau, berkilau, baru, ajaib'),
    ('tabler-wand', 'tongkat sihir, ajaib, otomatis')
) AS v(code, kw)
WHERE m."code" = v.code;
