-- Create Free Package
INSERT INTO "m_paket" ("id", "nama", "deskripsi", "harga", "status", "createdAt", "updatedAt")
VALUES (
  'paket-free-001',
  'Free',
  'Paket gratis dengan fitur dasar',
  0.00,
  true,
  NOW(),
  NOW()
)
ON CONFLICT DO NOTHING;

-- Create Demo Company
INSERT INTO "company" ("id", "nama", "alamat", "telepon", "email", "status", "paketId", "createdAt", "updatedAt")
VALUES (
  'company-demo-001',
  'Demo Company',
  'Jl. Demo No. 123, Jakarta',
  '021-12345678',
  'demo@company.com',
  true,
  'paket-free-001',
  NOW(),
  NOW()
)
ON CONFLICT DO NOTHING;

-- Create Super Admin User
INSERT INTO "user" ("id", "username", "email", "password", "tokenVersion", "createdAt", "verifikasi", "status", "updatedAt", "companyId", "roleId")
VALUES (
  'superadmin-user-001',
  'superadmin',
  'superadmin@example.com',
  '$2a$10$bn0E6PaatQg9wN41MudaZ.tyFOodVC3cPhAKDK4vJJZR/fAX1Gnaq',
  0,
  NOW(),
  true,
  true,
  NOW(),
  'company-demo-001',
  'superadmin-role-001'
)
ON CONFLICT DO NOTHING;

-- Create default global menus with hierarchical structure
INSERT INTO "menu" ("id", "nama", "path", "icon", "urutan", "parentId", "status", "createdAt", "updatedAt")
VALUES
  -- Main Menus (Level 1)
  ('menu-home', 'Home', '/home', 'tabler-smart-home', 1, NULL, true, NOW(), NOW()),
  ('menu-dashboard', 'Dashboard', '/dashboard', 'tabler-chart-pie', 0, NULL, true, NOW(), NOW()),
  ('menu-aset', 'Aset', '/aset/list', 'tabler-home-dollar', 2, NULL, true, NOW(), NOW()),
  ('menu-keuangan', 'Keuangan', '/keuangan/list', 'tabler-chart-histogram', 3, NULL,true, NOW(), NOW()),
  ('menu-penghuni', 'Penghuni', '/penghuni/list', 'tabler-friends', 4, NULL,true, NOW(), NOW()),

  -- Management Master Parent Menu
  ('menu-management', 'Management', NULL, 'tabler-settings', 5, NULL, true, NOW(), NOW()),
  ('menu-company', 'Company', '/management-master/company', 'tabler-building', 1, 'menu-management', true, NOW(), NOW()),
  ('menu-user', 'User', '/management-master/user', 'tabler-users', 2, 'menu-management', true, NOW(), NOW()),
  ('menu-role', 'Role', '/management-master/role', 'tabler-shield', 3, 'menu-management', true, NOW(), NOW()),
  ('menu-menu', 'Menu', '/management-master/menu', 'tabler-menu-2', 4, 'menu-management', true, NOW(), NOW()),
  ('menu-icon', 'Icon', '/management-master/icon', 'tabler-icons', 5, 'menu-management', true, NOW(), NOW()),
  ('menu-paket', 'Paket', '/management-master/paket', 'tabler-package', 6, 'menu-management', true, NOW(), NOW()),

  -- Master Data Parent Menu
  ('menu-master', 'Master Data', NULL, 'tabler-database', 6, NULL, true, NOW(), NOW()),
  ('menu-master-icon', 'Icon', '/master/icon/list', 'tabler-favicon', 1, 'menu-master', true, NOW(), NOW()),

  -- Setting Parent Menu
  ('menu-setting', 'Setting', NULL, 'tabler-adjustments', 7, NULL, true, NOW(), NOW()),
  ('menu-category-keuangan', 'Kategori Keuangan', '/setting/category-keuangan', 'tabler-category', 1, 'menu-setting', true, NOW(), NOW()),
  ('menu-setting-role', 'Role Setting', '/setting/role', 'tabler-shield-check', 2, 'menu-setting', true, NOW(), NOW())ON CONFLICT DO NOTHING;

-- Create Super Admin Role (global, no company)
INSERT INTO "role" ("id", "nama", "deskripsi", "status", "companyId", "createdAt", "updatedAt")
VALUES (
  'superadmin-role-001',
  'Super Admin',
  'Full system access with all permissions',
  true,
  NULL,
  NOW(),
  NOW()
)
ON CONFLICT DO NOTHING;

-- Assign menus to Free Package
-- Free package includes basic menus: Home, Aset, Keuangan, Penghuni
INSERT INTO "paket_menu" ("id", "paketId", "menuId", "createdAt", "updatedAt")
SELECT
  'pm-free-' || m.id,
  'paket-free-001',
  m.id,
  NOW(),
  NOW()
FROM "menu" m
ON CONFLICT ("paketId", "menuId") DO NOTHING;

-- Assign all menus to Super Admin role
INSERT INTO "menu_role" ("id", "roleId", "menuId", "createdAt", "updatedAt")
SELECT
  'rm-' || m.id,
  'superadmin-role-001',
  m.id,
  NOW(),
  NOW()
FROM "menu" m
ON CONFLICT ("roleId", "menuId") DO NOTHING;

-- Insert Tabler Icons into m_icon table
-- Total icons: 242
INSERT INTO "m_icon" ("id", "nama", "code", "createdById", "updatedById", "createdAt", "updatedAt")
SELECT
  icon_data.id,
  icon_data.nama,
  icon_data.code,
  'superadmin-user-001',
  'superadmin-user-001',
  NOW(),
  NOW()
FROM (VALUES
  ('icon-home', 'Home', 'tabler-home'),
  ('icon-dashboard', 'Dashboard', 'tabler-dashboard'),
  ('icon-menu', 'Menu', 'tabler-menu'),
  ('icon-menu-2', 'Menu 2', 'tabler-menu-2'),
  ('icon-dots', 'Dots', 'tabler-dots'),
  ('icon-dots-vertical', 'Dots Vertical', 'tabler-dots-vertical'),
  ('icon-chevron-down', 'Chevron Down', 'tabler-chevron-down'),
  ('icon-chevron-up', 'Chevron Up', 'tabler-chevron-up'),
  ('icon-chevron-left', 'Chevron Left', 'tabler-chevron-left'),
  ('icon-chevron-right', 'Chevron Right', 'tabler-chevron-right'),
  ('icon-arrow-left', 'Arrow Left', 'tabler-arrow-left'),
  ('icon-arrow-right', 'Arrow Right', 'tabler-arrow-right'),
  ('icon-arrow-up', 'Arrow Up', 'tabler-arrow-up'),
  ('icon-arrow-down', 'Arrow Down', 'tabler-arrow-down'),
  ('icon-x', 'X', 'tabler-x'),
  ('icon-check', 'Check', 'tabler-check'),
  ('icon-plus', 'Plus', 'tabler-plus'),
  ('icon-minus', 'Minus', 'tabler-minus'),
  ('icon-search', 'Search', 'tabler-search'),
  ('icon-filter', 'Filter', 'tabler-filter'),
  ('icon-settings', 'Settings', 'tabler-settings'),
  ('icon-adjustments', 'Adjustments', 'tabler-adjustments'),
  ('icon-user', 'User', 'tabler-user'),
  ('icon-users', 'Users', 'tabler-users'),
  ('icon-user-plus', 'User Plus', 'tabler-user-plus'),
  ('icon-user-minus', 'User Minus', 'tabler-user-minus'),
  ('icon-user-check', 'User Check', 'tabler-user-check'),
  ('icon-user-x', 'User X', 'tabler-user-x'),
  ('icon-user-circle', 'User Circle', 'tabler-user-circle'),
  ('icon-friends', 'Friends', 'tabler-friends'),
  ('icon-mood-happy', 'Mood Happy', 'tabler-mood-happy'),
  ('icon-mood-sad', 'Mood Sad', 'tabler-mood-sad'),
  ('icon-mood-smile', 'Mood Smile', 'tabler-mood-smile'),
  ('icon-building', 'Building', 'tabler-building'),
  ('icon-building-store', 'Building Store', 'tabler-building-store'),
  ('icon-building-bank', 'Building Bank', 'tabler-building-bank'),
  ('icon-building-factory', 'Building Factory', 'tabler-building-factory'),
  ('icon-building-warehouse', 'Building Warehouse', 'tabler-building-warehouse'),
  ('icon-cash', 'Cash', 'tabler-cash'),
  ('icon-coin', 'Coin', 'tabler-coin'),
  ('icon-currency-dollar', 'Currency Dollar', 'tabler-currency-dollar'),
  ('icon-currency-euro', 'Currency Euro', 'tabler-currency-euro'),
  ('icon-currency-pound', 'Currency Pound', 'tabler-currency-pound'),
  ('icon-currency-rupee', 'Currency Rupee', 'tabler-currency-rupee'),
  ('icon-credit-card', 'Credit Card', 'tabler-credit-card'),
  ('icon-wallet', 'Wallet', 'tabler-wallet'),
  ('icon-receipt', 'Receipt', 'tabler-receipt'),
  ('icon-chart-line', 'Chart Line', 'tabler-chart-line'),
  ('icon-chart-bar', 'Chart Bar', 'tabler-chart-bar'),
  ('icon-chart-pie', 'Chart Pie', 'tabler-chart-pie'),
  ('icon-chart-histogram', 'Chart Histogram', 'tabler-chart-histogram'),
  ('icon-trending-up', 'Trending Up', 'tabler-trending-up'),
  ('icon-trending-down', 'Trending Down', 'tabler-trending-down'),
  ('icon-report', 'Report', 'tabler-report'),
  ('icon-report-analytics', 'Report Analytics', 'tabler-report-analytics'),
  ('icon-home-dollar', 'Home Dollar', 'tabler-home-dollar'),
  ('icon-home-2', 'Home 2', 'tabler-home-2'),
  ('icon-smart-home', 'Smart Home', 'tabler-smart-home'),
  ('icon-door', 'Door', 'tabler-door'),
  ('icon-bed', 'Bed', 'tabler-bed'),
  ('icon-armchair', 'Armchair', 'tabler-armchair'),
  ('icon-bath', 'Bath', 'tabler-bath'),
  ('icon-key', 'Key', 'tabler-key'),
  ('icon-lock', 'Lock', 'tabler-lock'),
  ('icon-lock-open', 'Lock Open', 'tabler-lock-open'),
  ('icon-mail', 'Mail', 'tabler-mail'),
  ('icon-message', 'Message', 'tabler-message'),
  ('icon-message-circle', 'Message Circle', 'tabler-message-circle'),
  ('icon-phone', 'Phone', 'tabler-phone'),
  ('icon-phone-call', 'Phone Call', 'tabler-phone-call'),
  ('icon-bell', 'Bell', 'tabler-bell'),
  ('icon-bell-ringing', 'Bell Ringing', 'tabler-bell-ringing'),
  ('icon-notification', 'Notification', 'tabler-notification'),
  ('icon-send', 'Send', 'tabler-send'),
  ('icon-inbox', 'Inbox', 'tabler-inbox'),
  ('icon-file', 'File', 'tabler-file'),
  ('icon-file-text', 'File Text', 'tabler-file-text'),
  ('icon-file-plus', 'File Plus', 'tabler-file-plus'),
  ('icon-file-minus', 'File Minus', 'tabler-file-minus'),
  ('icon-files', 'Files', 'tabler-files'),
  ('icon-folder', 'Folder', 'tabler-folder'),
  ('icon-folder-plus', 'Folder Plus', 'tabler-folder-plus'),
  ('icon-clipboard', 'Clipboard', 'tabler-clipboard'),
  ('icon-clipboard-list', 'Clipboard List', 'tabler-clipboard-list'),
  ('icon-notes', 'Notes', 'tabler-notes'),
  ('icon-notebook', 'Notebook', 'tabler-notebook'),
  ('icon-book', 'Book', 'tabler-book'),
  ('icon-bookmark', 'Bookmark', 'tabler-bookmark'),
  ('icon-photo', 'Photo', 'tabler-photo'),
  ('icon-camera', 'Camera', 'tabler-camera'),
  ('icon-video', 'Video', 'tabler-video'),
  ('icon-music', 'Music', 'tabler-music'),
  ('icon-microphone', 'Microphone', 'tabler-microphone'),
  ('icon-volume', 'Volume', 'tabler-volume'),
  ('icon-volume-2', 'Volume 2', 'tabler-volume-2'),
  ('icon-play', 'Play', 'tabler-play'),
  ('icon-pause', 'Pause', 'tabler-pause'),
  ('icon-stop', 'Stop', 'tabler-stop'),
  ('icon-download', 'Download', 'tabler-download'),
  ('icon-upload', 'Upload', 'tabler-upload'),
  ('icon-cloud', 'Cloud', 'tabler-cloud'),
  ('icon-cloud-upload', 'Cloud Upload', 'tabler-cloud-upload'),
  ('icon-cloud-download', 'Cloud Download', 'tabler-cloud-download'),
  ('icon-edit', 'Edit', 'tabler-edit'),
  ('icon-pencil', 'Pencil', 'tabler-pencil'),
  ('icon-eraser', 'Eraser', 'tabler-eraser'),
  ('icon-trash', 'Trash', 'tabler-trash'),
  ('icon-copy', 'Copy', 'tabler-copy'),
  ('icon-cut', 'Cut', 'tabler-cut'),
  ('icon-paste', 'Paste', 'tabler-paste'),
  ('icon-save', 'Save', 'tabler-save'),
  ('icon-printer', 'Printer', 'tabler-printer'),
  ('icon-scan', 'Scan', 'tabler-scan'),
  ('icon-qrcode', 'Qrcode', 'tabler-qrcode'),
  ('icon-barcode', 'Barcode', 'tabler-barcode'),
  ('icon-shield', 'Shield', 'tabler-shield'),
  ('icon-shield-check', 'Shield Check', 'tabler-shield-check'),
  ('icon-shield-lock', 'Shield Lock', 'tabler-shield-lock'),
  ('icon-eye', 'Eye', 'tabler-eye'),
  ('icon-eye-off', 'Eye Off', 'tabler-eye-off'),
  ('icon-fingerprint', 'Fingerprint', 'tabler-fingerprint'),
  ('icon-password', 'Password', 'tabler-password'),
  ('icon-alert-circle', 'Alert Circle', 'tabler-alert-circle'),
  ('icon-alert-triangle', 'Alert Triangle', 'tabler-alert-triangle'),
  ('icon-info-circle', 'Info Circle', 'tabler-info-circle'),
  ('icon-help', 'Help', 'tabler-help'),
  ('icon-question-mark', 'Question Mark', 'tabler-question-mark'),
  ('icon-circle-check', 'Circle Check', 'tabler-circle-check'),
  ('icon-circle-x', 'Circle X', 'tabler-circle-x'),
  ('icon-exclamation-mark', 'Exclamation Mark', 'tabler-exclamation-mark'),
  ('icon-calendar', 'Calendar', 'tabler-calendar'),
  ('icon-calendar-event', 'Calendar Event', 'tabler-calendar-event'),
  ('icon-clock', 'Clock', 'tabler-clock'),
  ('icon-alarm', 'Alarm', 'tabler-alarm'),
  ('icon-hourglass', 'Hourglass', 'tabler-hourglass'),
  ('icon-history', 'History', 'tabler-history'),
  ('icon-map', 'Map', 'tabler-map'),
  ('icon-map-pin', 'Map Pin', 'tabler-map-pin'),
  ('icon-location', 'Location', 'tabler-location'),
  ('icon-compass', 'Compass', 'tabler-compass'),
  ('icon-route', 'Route', 'tabler-route'),
  ('icon-directions', 'Directions', 'tabler-directions'),
  ('icon-shopping-cart', 'Shopping Cart', 'tabler-shopping-cart'),
  ('icon-shopping-bag', 'Shopping Bag', 'tabler-shopping-bag'),
  ('icon-basket', 'Basket', 'tabler-basket'),
  ('icon-gift', 'Gift', 'tabler-gift'),
  ('icon-tag', 'Tag', 'tabler-tag'),
  ('icon-tags', 'Tags', 'tabler-tags'),
  ('icon-ticket', 'Ticket', 'tabler-ticket'),
  ('icon-package', 'Package', 'tabler-package'),
  ('icon-box', 'Box', 'tabler-box'),
  ('icon-truck-delivery', 'Truck Delivery', 'tabler-truck-delivery'),
  ('icon-share', 'Share', 'tabler-share'),
  ('icon-heart', 'Heart', 'tabler-heart'),
  ('icon-star', 'Star', 'tabler-star'),
  ('icon-thumb-up', 'Thumb Up', 'tabler-thumb-up'),
  ('icon-thumb-down', 'Thumb Down', 'tabler-thumb-down'),
  ('icon-flag', 'Flag', 'tabler-flag'),
  ('icon-device-desktop', 'Device Desktop', 'tabler-device-desktop'),
  ('icon-device-laptop', 'Device Laptop', 'tabler-device-laptop'),
  ('icon-device-mobile', 'Device Mobile', 'tabler-device-mobile'),
  ('icon-device-tablet', 'Device Tablet', 'tabler-device-tablet'),
  ('icon-wifi', 'Wifi', 'tabler-wifi'),
  ('icon-bluetooth', 'Bluetooth', 'tabler-bluetooth'),
  ('icon-usb', 'Usb', 'tabler-usb'),
  ('icon-plug', 'Plug', 'tabler-plug'),
  ('icon-battery', 'Battery', 'tabler-battery'),
  ('icon-battery-charging', 'Battery Charging', 'tabler-battery-charging'),
  ('icon-cpu', 'Cpu', 'tabler-cpu'),
  ('icon-server', 'Server', 'tabler-server'),
  ('icon-palette', 'Palette', 'tabler-palette'),
  ('icon-brush', 'Brush', 'tabler-brush'),
  ('icon-color-picker', 'Color Picker', 'tabler-color-picker'),
  ('icon-paint', 'Paint', 'tabler-paint'),
  ('icon-layers', 'Layers', 'tabler-layers'),
  ('icon-layout', 'Layout', 'tabler-layout'),
  ('icon-template', 'Template', 'tabler-template'),
  ('icon-grid-dots', 'Grid Dots', 'tabler-grid-dots'),
  ('icon-square', 'Square', 'tabler-square'),
  ('icon-circle', 'Circle', 'tabler-circle'),
  ('icon-triangle', 'Triangle', 'tabler-triangle'),
  ('icon-sun', 'Sun', 'tabler-sun'),
  ('icon-moon', 'Moon', 'tabler-moon'),
  ('icon-cloud-rain', 'Cloud Rain', 'tabler-cloud-rain'),
  ('icon-cloud-snow', 'Cloud Snow', 'tabler-cloud-snow'),
  ('icon-wind', 'Wind', 'tabler-wind'),
  ('icon-temperature', 'Temperature', 'tabler-temperature'),
  ('icon-leaf', 'Leaf', 'tabler-leaf'),
  ('icon-plant', 'Plant', 'tabler-plant'),
  ('icon-tree', 'Tree', 'tabler-tree'),
  ('icon-coffee', 'Coffee', 'tabler-coffee'),
  ('icon-cup', 'Cup', 'tabler-cup'),
  ('icon-pizza', 'Pizza', 'tabler-pizza'),
  ('icon-apple', 'Apple', 'tabler-apple'),
  ('icon-lemon', 'Lemon', 'tabler-lemon'),
  ('icon-ball-basketball', 'Ball Basketball', 'tabler-ball-basketball'),
  ('icon-ball-football', 'Ball Football', 'tabler-ball-football'),
  ('icon-bike', 'Bike', 'tabler-bike'),
  ('icon-run', 'Run', 'tabler-run'),
  ('icon-walk', 'Walk', 'tabler-walk'),
  ('icon-star-filled', 'Star Filled', 'tabler-star-filled'),
  ('icon-heart-filled', 'Heart Filled', 'tabler-heart-filled'),
  ('icon-circle-filled', 'Circle Filled', 'tabler-circle-filled'),
  ('icon-square-filled', 'Square Filled', 'tabler-square-filled'),
  ('icon-infinity', 'Infinity', 'tabler-infinity'),
  ('icon-hash', 'Hash', 'tabler-hash'),
  ('icon-at', 'At', 'tabler-at'),
  ('icon-percentage', 'Percentage', 'tabler-percentage'),
  ('icon-arrow-narrow-up', 'Arrow Narrow Up', 'tabler-arrow-narrow-up'),
  ('icon-arrow-narrow-down', 'Arrow Narrow Down', 'tabler-arrow-narrow-down'),
  ('icon-arrow-narrow-left', 'Arrow Narrow Left', 'tabler-arrow-narrow-left'),
  ('icon-arrow-narrow-right', 'Arrow Narrow Right', 'tabler-arrow-narrow-right'),
  ('icon-arrows-maximize', 'Arrows Maximize', 'tabler-arrows-maximize'),
  ('icon-arrows-minimize', 'Arrows Minimize', 'tabler-arrows-minimize'),
  ('icon-refresh', 'Refresh', 'tabler-refresh'),
  ('icon-rotate', 'Rotate', 'tabler-rotate'),
  ('icon-flip-horizontal', 'Flip Horizontal', 'tabler-flip-horizontal'),
  ('icon-flip-vertical', 'Flip Vertical', 'tabler-flip-vertical'),
  ('icon-brand-facebook', 'Brand Facebook', 'tabler-brand-facebook'),
  ('icon-brand-twitter', 'Brand Twitter', 'tabler-brand-twitter'),
  ('icon-brand-instagram', 'Brand Instagram', 'tabler-brand-instagram'),
  ('icon-brand-linkedin', 'Brand Linkedin', 'tabler-brand-linkedin'),
  ('icon-brand-youtube', 'Brand Youtube', 'tabler-brand-youtube'),
  ('icon-brand-google', 'Brand Google', 'tabler-brand-google'),
  ('icon-brand-github', 'Brand Github', 'tabler-brand-github'),
  ('icon-brand-whatsapp', 'Brand Whatsapp', 'tabler-brand-whatsapp'),
  ('icon-favicon', 'Favicon', 'tabler-favicon'),
  ('icon-atom', 'Atom', 'tabler-atom'),
  ('icon-award', 'Award', 'tabler-award'),
  ('icon-badge', 'Badge', 'tabler-badge'),
  ('icon-certificate', 'Certificate', 'tabler-certificate'),
  ('icon-crown', 'Crown', 'tabler-crown'),
  ('icon-diamond', 'Diamond', 'tabler-diamond'),
  ('icon-flame', 'Flame', 'tabler-flame'),
  ('icon-lightning', 'Lightning', 'tabler-lightning'),
  ('icon-magnet', 'Magnet', 'tabler-magnet'),
  ('icon-puzzle', 'Puzzle', 'tabler-puzzle'),
  ('icon-rocket', 'Rocket', 'tabler-rocket'),
  ('icon-sparkles', 'Sparkles', 'tabler-sparkles'),
  ('icon-wand', 'Wand', 'tabler-wand')
) AS icon_data(id, nama, code)
ON CONFLICT ("code") DO NOTHING;
